### ISSUE TITLE
Master - ping nodes in configurable time gaps

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#21]
We configure a time span that after each master must refresh information about all nodes, for example every 5 seconds master asks again all connected nodes for their information (cpu + mem + sqlite file size)

**Comment by davidmigloz** [comment]
Master pings nodes every x milliseconds (x is setted up in conf file -> spanPingingTime ). If a node is unreachable or it does not aswer in a given timeout (conf file ->timeout) the node is marked as down. Otherwise, its information is updated.
