### ISSUE TITLE
Travis - tests and unittests integration

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#23]
We should be able to run tests automatically by travis - check if it isn't possible to run also integration tests using for example docker. If no then configure it to run only unittests

**Comment by dzitkowskik** [comment]
You dont have to use docker. Just fix this travis quickly!!

**Comment by dzitkowskik** [comment]
partially fixed:) not failing but needed integration with docker...

**Comment by dawidppp** [comment]
Sample of integration test:
https://github.com/dzitkowskik/mini-dos/blob/f6f2a222c4e6bd601851ee53f83f895969d7833e/integrationTests/pl/pw/edu/mini/dos/client/ClientMasterSimpleITest.java
Sample of unit test (without Mockito):
https://github.com/dzitkowskik/mini-dos/commit/cc9ce0fdf1e03c66a2dd3f9eace755bf38360262
Tutorial soon.
