### ISSUE TITLE
Master - Insert data replication

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#27]
When node asks master for the nodes to insert new data, Master should answer him with a list of other nodes to insert that data. Replication factor must be configurable in some external file or by master argument on startup. Before master answer the node, he inserts data with information about there these rows will be stored in his in memory db. (RowId, NodeId, TableId) - for each row and node inserted to particular table.

**Comment by davidmigloz** [comment]
Master chooses _n_ nodes randomly, where _n_ is equal to replication factor. If number of available nodes in less than replication factor `ErrorEnum.NOT_ENOUGH_NODES` is sent (the list of nodes sent is null).  
Master registers the metadata of the insert (RowId, TableId, NodesIds). If the user is trying to make an insert in a non-existing table, `ErrorEnum.TABLE_NOT_EXIST` is sent (the list of nodes sent is null).  
So the task is ready.
