### ISSUE TITLE
Master - Tasks

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#34]
Master should register all ongoing tasks and their statuses, we should also be able to query them (see all active tasks) also with history (which tasks failed, which completed successfully). We should also know wchich node is doing which task and so on... It will be helpful for example when we will try to do the task again using different node in case of failure.

**Comment by davidmigloz** [comment]
Master register all ongoing tasks, their statuses and the node which is doing the task.
Pending: query status of the tasks

**Comment by dzitkowskik** [comment]
Quering taska can be done from master console as one of admin commands. Lets say command will look like that
`SELECT * FROM tasks;`

**Comment by davidmigloz** [comment]
Query tasks and nodes done:

``` sql
SELECT * FROM NODES;
> #0: UP (LA 1.47, DB size 3.00KB, Free Mem. 55.01MB)
> #1: UP (LA 1.47, DB size 3.00KB, Free Mem. 43.25MB)

SELECT 0 FROM NODES;
> #0: UP (LA 1.47, DB size 3.00KB, Free Mem. 55.01MB)

SELECT * FROM TASKS;
> #0 (n1): finished
> #1 (n1): aborted
> #2 (n0): finished

SELECT 1 FROM TASKS;
> #1 (n1): aborted
```
