### ISSUE TITLE
Testing inserts

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#35]
We should have unittests for inserts in node as well as integration tests of inserting data to our distributed db. You should also test here if we create table successfully, because table must be created first. Look carefully on table creation. When user creates a table it should be created on every node.

**Comment by dawidppp** [comment]
https://github.com/dzitkowskik/mini-dos/commit/fc5f3481b332542f5ab55f192f7c45cdb5ed978f
https://github.com/dzitkowskik/mini-dos/commit/1ac64b398b56d0057aa1c90af80a6fada8a6de3e
