### ISSUE TITLE
Master - Creating Tables

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#36]
When node gets CREATE TABLE sql query then it should register table creation in master. Master should save sql of table creation as well its name. Node then executes create table query in his db as well as all nodes sent to him by master. 

Secondly, when new node is registered in master, master sends him request to update his db with table creation and attaches a list of table names with sql queries to execute. Node check if it has table with that name in his db, and if it doesn't he executes that sql query (to create this table).

**Comment by dzitkowskik** [comment]
This create table in node should be implemented like inserts - using 2 phase commit, nearly the same code probably, but it must also send to master create sql to store it there for later

**Comment by davidmigloz** [comment]
Master registers the table name and create statement in its in-memory database.

Pending: when node registers in master send him all create tables.

**Comment by davidmigloz** [comment]
Master sends create tables staments to node when it registers. For doing that it uses a new method in MasterNodeInterface `createTables()` .

Pending: implement `createTables()`  in node.

**Comment by davidmigloz** [comment]
Task ready.
