### ISSUE TITLE
Master task timestamp

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#37]
When master gets query from client, it should create task with timestamp and attach this timestamp with id of the task when it passed data further to node.

**Comment by davidmigloz** [comment]
Is it enough to use the task id as a timestamp? I think it is, right?

**Comment by dzitkowskik** [comment]
I think it should for now. Then we need only one additional column for each table:)

**Comment by davidmigloz** [comment]
So then this task is ready :)
