### ISSUE TITLE
Testing selects

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#39]
Simple integration tests for selects. For now SELECT \* FROM <table> you must be sure the data should exist there. Also what will happen if we want to have multiple records with the same data? (We use distinct to concatenate tables in Node properly). Think about that

**Comment by dawidppp** [comment]
with where: https://github.com/dzitkowskik/mini-dos/commit/1006979a0aa8f94e43e5790b8756db25dbdb03b8
and 5 next commits.
