### ISSUE TITLE
Functional specification

### ISSUE THREAD

**Issue by davidmigloz** [dzitkowskik/mini-dos#4]
Using the MoSCoW method (https://en.wikipedia.org/wiki/MoSCoW_method).

**Comment by dzitkowskik** [comment]
Why do we want to use that?

**Comment by davidmigloz** [comment]
Functional specification or MoSCoW method?

**Comment by dzitkowskik** [comment]
MoSCoW

**Comment by davidmigloz** [comment]
We write the list of functional requirements and then we classified them according to this method. So all the requirements classified as:
- **Must have:** must be implemented in order to succeed.
- **Should have:** would be advisable to be implemented but they are not critical.
- **Could have:** are possible improvements or extra features.
- **Won't have:** would be nice to implement them but we are not going to do it (because of time, money, etc.).

**Comment by dzitkowskik** [comment]
Good as it is a documentation part I will assign it for now to Ozan but I want us all to think about it and add our sugestions. Lets do it now only for first deadline (this first part where nodes should be able to store and select data they own and master should redirect queries to some registered node)

**Comment by dzitkowskik** [comment]
As it is a documentation it should be done by Ozan actually

**Comment by dzitkowskik** [comment]
Added to Wiki in Specification tab (I used MoSCoW)
