### ISSUE TITLE
Node - Sending Select result from node to node

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#42]
There must be a way to somehow serialize ResultSet that we will get after execution of select query on one node to send it to another. After that it must be inserted to the same table in destination node but to in memory database (here a query to create this table will be needed from master).

(*) this is the point of this issue

Select process will look like that:
1. Get create table statements from master for needed tables
2. Create them in in memory database
3. Execute selects (select \* from <table>) in all nodes pointed by master (these which contain that data) for all needed tables
4. Serialize somehow ResultSets and send it to coordinating node   (*)
5. Coordinating node inserts (unserialized data) to created tables in in memory db performing distinct on our internal id 
6. Perform sql query (our SELECT from client) on in memory db, then return result

**Comment by davidmigloz** [comment]
Solved with `SerializableResultSet` class.
Issue done.
