### ISSUE TITLE
Sending serialized ResultSet from Node to Node

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#50]
Implement a way to send query result from node to node

**Comment by dzitkowskik** [comment]
Done using DbUtils

**Comment by davidmigloz** [comment]
Actually, we are not using DbUtils anymore. I implemented a Result Set Serializable and a method that fill it from the original Result Set. Using DbUtils did not provide us any advantage.

**Comment by dzitkowskik** [comment]
Sorry my bad, you are right:)
