### ISSUE TITLE
Additional column - row version(id) + Inserts

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#55]
Every table in the system should have one more column generated by us  called _VERSION_. This column should be automatically added to table in node when it creates a table. It will be used for version of a row. 
Additionaly when data is inserted to a row, master in response with metadata sends new generated internal id for this insert. Use it to fill _VERSION_ column when inserting data to node SQLite DB.

**Comment by davidmigloz** [comment]
Done.
