### ISSUE TITLE
Master - Node (administrator API)

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#61]
Create API for killing, manually checking statuses of nodes and so on:) It should be accessible by commands through Master console. Add also some commands to list tasks and nodes.

**Comment by davidmigloz** [comment]
Quering info of nodes done. 
Pending: killing nodes

**Comment by davidmigloz** [comment]
Killing nodes from master done.

``` sql
KILL * FROM NODES;
> All nodes killed

KILL 0 FROM NODES;
> Node 0 killed
```
