### ISSUE TITLE
Update query #56 (TESTS)

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#63]
Tests for Update query #56

**Comment by dawidppp** [comment]
Simple ITest: https://github.com/dzitkowskik/mini-dos/commit/3f2d807e55a227cd242450d947c9878cac3a2b9d

**Comment by dawidppp** [comment]
https://github.com/dzitkowskik/mini-dos/commit/5281199a3c2a03a0ac3ee3355817bcc41775af64
