### ISSUE TITLE
Delete query #57 (TESTS)

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#64]
Tests for Delete query #57

**Comment by dzitkowskik** [comment]
Implementing just like Insert (2 phase commit) with information from master from which nodes we should delete data.

**Comment by dzitkowskik** [comment]
Ready for testing!

**Comment by dawidppp** [comment]
Simple ITest: https://github.com/dzitkowskik/mini-dos/commit/0552e63e0d7cce0f56fa57aa8029689af5c192e1

**Comment by dawidppp** [comment]
https://github.com/dzitkowskik/mini-dos/commit/7d12626e367ecf9dc28c872860bda5c9fcdb6cb5
