### ISSUE TITLE
Create/Alter table (TESTS)

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#68]
Tests for creating and altering tables:
1. FIRST TEST CASE - we create two tables A and B, and alter A, then we insert data to them, everything should be successful, check if alter worked
2. SECOND TEST CASE - we create tables A and B, do some ALTER statements which must be in good order to work, like first create new column and then add sth property to it or sth. Then make new node to register to the system. New node should have recreated all create and alter statements, and be able to insert new data to them.

**Comment by dawidppp** [comment]
Our parser library parse Alter Table queries in different way than SQLite.
