### ISSUE TITLE
Persistance of data

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#77]
Check persistance and make a test for it. So we connect some number of nodes, then create table and put some data. After restart of some nodes or master or whole system, data should be still available.
Look carefully on situation where we have multiple nodes on the same machine. For example node 1, 2 and 3. Each node should have an ID, and we should be able to start node with its ID/Name. Then it should use database with name of that id/name. So when we kill nodes 1 and 3 we should be able to start them again with the same data - with their previous databases:) I hope it is clear what should be done in this issue:)

**Comment by davidmigloz** [comment]
At the moment, each time you run a node a db with a random name is created. 
I did that because if not there was conflicts when you run several nodes in the same machine (like we do in IntellJ), because all of them used the same db.
So disable that to test this.

**Comment by dzitkowskik** [comment]
Yes, but you can leave it that way, but add an argument for node as -id=nodeOne and that node will use database with name nodeOne.db

**Comment by davidmigloz** [comment]
Yeah you're right, that's a better option.
