### ISSUE TITLE
Alter table operations

### ISSUE THREAD

**Issue by davidmigloz** [dzitkowskik/mini-dos#83]
We have been researching that bug.
Summary: 
1. SQLite just supports following `ALTER TABLE` operations:
    + Rename table: `ALTER TABLE <table_name> RENAME TO <new_table_name>;`
    + Add column (not standard SQL): `ALTER TABLE <table_name> ADD COLUMN <new_column_type> <new_column_type> ;`
2. Parser library does not support:
    + Rename table: `ALTER TABLE <table_name> RENAME TO <new_table_name>;`
3. Parser library just supports following `ALTER TABLE` operations:
    + Add column: `ALTER TABLE <table_name> ADD <new_column_type> (<new_column_name>)`
    + Drop column: `ALTER TABLE <table_name> DROP <column_name>`

Conclusions:
- We cannot parse rename table operations.
- We cannot add columns because SQLite syntax is not standart.
- We cannot drop columns because is not supported by SQLite.

Options:
- Not support `ALTER TABLE` operations.
- Find another parser only for alter table.
- Create our own parser for alter table, it would be an abstract class and the original parser will extends it (much work).

**Comment by dzitkowskik** [comment]
Solved partially
